docker run --rm \
        -e "KMS_PKCS11_CONFIG=/mnt/libkmsp11-config.yaml" \
        -e GOOGLE_APPLICATION_CREDENTIALS="/app/.config/gcloud/application_default_credentials.json" \
        -e LD_LIBRARY_PATH=/app \
        --mount type=bind,source="${HOME}/.config/gcloud,target=/app/.config/gcloud" \
        -v "${PWD}/libkmsp11-config.yaml:/mnt/libkmsp11-config.yaml" \
        -v "${PWD}/openssl_sign.cnf:/mnt/openssl_sign.cnf" \
        "mozilla/autograph:latest" openssl ca \
        -startdate 20241022000000Z \
        -enddate 21010519000000Z \
        -selfsign \
        -keyfile content-signature-and-addons-root-202410-dev \
        -policy policy_match \
        -extensions content_signature_and_addons_root_ca \
        -config "/mnt/openssl_sign.cnf" \
        -in content-signature-and-addons-root-202410-dev.csr \
        -out content-signature-and-addons-root-202410-dev.crt \
        -notext \
        -engine pkcs11 \
        -keyform engine \
        -batch
