build:
	pip install ecdsa -t .
	pip install requests -t .
	pip install requests_hawk -t .
	zip -r autograph-lambda-python-healthcheck.zip *
clean:
	rm -rf autograph-lambda-python-healthcheck.zip mohawk* six* ecdsa* requests*

